apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

