apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - name: spring-boot-hello-world
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
