apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world
spec:
  selector:
    app: spring-boot-hello-world
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
